apiVersion: v1
kind: Service
metadata:
  name: supply-chain-app
spec:
  type: NodePort   # Use LoadBalancer if you are on a cloud provider
  selector:
    app: supply-chain-app
  ports:
    - protocol: TCP
      port: 3000          # Port inside the pod
      targetPort: 3000    # Container port
      nodePort: 32000     # External port on the node (30000-32767)
